$font = Monospace

general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 2, linear
    animation = fadeOut, 1, 2, linear
    # animation = inputFieldDots, 1, 0, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
}

input-field {
    monitor =
    size = 240, 36
    outline_thickness = 2
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgba(c6a0f6ee) rgba(f5bde6ee) 45deg
    check_color = rgba(89b4faee) rgba(f5c2e7ee) 45deg
    fail_color = rgba(f38ba8ee)

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 15

    font_family = $font
    font_size = 12
    placeholder_text = password
    fail_text = $PAMFAIL

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    # dots_size = 0.4
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, -20
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME
    font_size = 48
    font_family = $font

    position = -30, 0
    halign = right
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = 24
    font_family = $font

    position = -30, -80
    halign = right
    valign = top
}
