#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II III IV V
DEFAULT_MONITOR="eDP-1"
bspc wm -O $DEFAULT_MONITOR $(xrandr -q | grep " connected" | cut -d" " -f1 | grep -v $DEFAULT_MONITOR | tr "\n" " ")
for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    if [[ $m == $DEFAULT_MONITOR ]]; then
        bspc monitor $m -d I II III IV V VI VII
    else
        bspc monitor $m -d VI VII VIII IX X
    fi
done

bspc config border_width         2
bspc config window_gap          4
bspc config top_padding 32

bspc config focused_border_color \#425047
bspc config normal_border_color \#2d353b

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

bspc rule -a steam desktop='^3' focus=off
bspc rule -a Spotify desktop='^4' focus=off
bspc rule -a 'Friends List' state=floating focus=off
bspc rule -a 'Steam - News' state=floating focus=off
bspc rule -a Nm-connection-editor state=floating
bspc rule -a 'cinnamon-settings network' state=floating
bspc rule -a Gpick state=floating
bspc rule -a MessageWin state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Yad state=floating
bspc rule -a Tk state=floating
bspc rule -a tk state=floating
bspc rule -a notificationtoasts_6_desktop state=floating focus=off

~/.fehbg

~/.config/polybar/start.sh
picom -b &
/usr/bin/dunst &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# nm-applet --indicator &
xsetroot -cursor_name left_ptr
dbus-update-activation-environment DISPLAY
