;==========================================================
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[c]
bg = #282C33
bg-dim = #21252B
fg = #ABB2BF
red = #E06B74
grey1 = #5C6370
green = #C778DD

[bar/example]
width = 100%
height = 32

fixed-center = true

bottom = false

background = ${c.bg}
foreground = ${c.fg}

border-size = 0
border-color = ${c.bg}

padding-left = 1
padding-right = 1

module-margin = 1

separator =

font-0 = FiraCode Nerd Font:size=11;4
font-1 = FiraCode Nerd Font Mono:size=18;3
font-2 = Noto Color Emoji:scale=6;4

modules-left = dmenu powermenu loginmenu bspwm xwindow
modules-center = xkill datetime
modules-right = backlight pulseaudio cpu memory wlan battery

tray-position = right

;wm-restack = generic
wm-restack = bspwm
;wm-restack = i3

override-redirect = false

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = false

[bar/second]
monitor = ${env:MONITOR:}
width = 100%
height = 32

fixed-center = true

bottom = false

background = ${c.bg}
foreground = ${c.fg}

border-size = 0
border-color = ${c.bg}

padding-left = 1
padding-right = 1

module-margin = 1

separator =

font-0 = FiraCode Nerd Font:size=11;4
font-1 = FiraCode Nerd Font Mono:size=18;3
font-2 = Noto Color Emoji:scale=6;4

modules-left = dmenu powermenu loginmenu bspwm xwindow
modules-center = xkill datetime
modules-right = backlight pulseaudio cpu memory eth wlan battery

tray-position = right

wm-restack = bspwm
;wm-restack = i3

override-redirect = false

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = false


[module/xwindow]
type = internal/xwindow
format = <label>
label-empty = ""
label = %title:0:50:...%

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
blacklist-1 = scroll lock

format-prefix = "󰌌 "
format-prefix-font = 2
format-prefix-foreground = ${c.green}

label-layout = %layout%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /
mount-1 = /home

label-mounted = %{F#c678dd}%mountpoint%%{F-}  %percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${c.grey1}

[module/bspwm]
type = internal/bspwm

enable-click = true
enable-scroll = true
reverse-scroll = false
pin-workspaces = true

ws-icon-0 = I;󰈹
ws-icon-1 = II;
ws-icon-2 = III;󰓓
ws-icon-3 = IV;󰝚
ws-icon-4 = V;󰇘
ws-icon-5 = VI;󰇘
ws-icon-6 = VII;󰇘
ws-icon-7 = VIII;󰇘
ws-icon-8 = IX;󰇘
ws-icon-9 = X;󰇘

format = <label-state>
format-font = 2

label-focused = %icon%
label-focused-padding = 1
label-focused-background = ${c.bg-dim}

label-occupied = %icon%
label-occupied-padding = 1

label-urgent = %icon%
label-urgent-padding = 1

label-empty = %icon%
label-empty-padding = 1

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "󰍛 "
format-prefix-font = 2
format-prefix-foreground = ${c.green}
label = %percentage:2%%

[module/memory]
type = internal/memory
interval = 2
format-prefix = "󰄨 "
format-prefix-font = 2
format-prefix-foreground = ${c.green}
label = %gb_used%

[module/wlan]
type = internal/network
interval = 5

interface = wlan0
interface-type = wireless

format-connected = <ramp-signal> <label-connected>
format-connected-foreground = ${c.green}
format-connected-prefix = "%{A1:cinnamon-settings network:} "
format-connected-prefix-font = 2
format-connected-prefix-foreground = ${c.green}
format-disconnected = <label-disconnected>

label-connected = %essid%%{A} : %{A1:nm-connection-editor:}%local_ip%%{A}
label-connected-foreground = ${c.fg}

label-disconnected = 󰤭 %ifname% disconnected
label-disconnected-foreground = ${c.grey1}

ramp-signal-0 = 󰤯
ramp-signal-1 = 󰤟
ramp-signal-2 = 󰤢
ramp-signal-3 = 󰤥
ramp-signal-4 = 󰤨

[module/eth]
type = internal/network
interval = 5

interface-type = wired

format-connected = <label-connected>
format-connected-prefix = "%{A3:nm-connection-editor:}󰈀 "
format-connected-prefix-font = 2
format-connected-prefix-foreground = ${c.green}
format-disconnected = <label-disconnected>

label-connected = %local_ip%%{A}

label-disconnected = %ifname% disconnected
label-disconnected-foreground = ${c.grey1}

[module/datetime]
type = internal/date

date = %A, %d %B
date-alt = %d-%m-%Y

time = %H:%M:%S
time-alt = %H:%M:%S

label-foreground = ${c.fg}
label = %date% %time%

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "󰕾 "
format-volume-prefix-font = 2
format-volume-prefix-foreground = ${c.green}
format-volume = <label-volume>

label-volume = %percentage%%

format-muted-prefix = "󰖁 "
format-muted-prefix-font = 2
format-muted-foreground = ${c.grey1}
format-muted = <label-muted>

label-muted = "..."

click-right = pavucontrol &

[module/battery]
type = internal/battery

full-at = 99

low-at = 5

battery = BAT1
adapter = ADP1

poll-interval = 5

; see "man date" for details on how to format the time string
; NOTE: if you want to use syntax tags here you need to use %%{...}
; Default: %H:%M:%S
time-format = %H:%M


format-charging = <label-charging>
format-charging-prefix = "󰂄 "
format-charging-prefix-foreground = ${c.green}
format-discharging = <ramp-capacity> <label-discharging>
format-discharging-foreground = ${c.green}
format-full = <label-full>
format-full-prefix = "󰁹 "
format-full-prefix-foreground = ${c.green}
format-low = 󰂃 <label-low>
format-low-foreground = ${c.alert}


label-charging = %percentage%%, ~%time% left
label-discharging = %percentage%%, ~%time% left
label-discharging-foreground = ${c.fg}
label-full = battery full
label-low = %percentage%, ~%time% left!

ramp-capacity-0 = 󰂎
ramp-capacity-1 = 󰁺
ramp-capacity-2 = 󰁻
ramp-capacity-3 = 󰁼
ramp-capacity-4 = 󰁽
ramp-capacity-5 = 󰁾
ramp-capacity-6 = 󰁿
ramp-capacity-7 = 󰁿
ramp-capacity-8 = 󰂁
ramp-capacity-9 = 󰂂

[settings]
screenchange-reload = true
pseudo-transparency = true

[module/kernel]
type = custom/script
exec = uname -r
tail = false
interval = 1024

[module/dmenu]
type = custom/text
content ="󰣐"
content-font = 2
content-foreground = ${c.green}
click-left = dmenu_drun -d 'dmenu -i -b -p drun'

[module/xkill]
type = custom/text
content ="󰧻"
content-font = 2
content-foreground = ${c.red}
click-left = sleep 0.1 && xkill > /dev/null 2>&1 &

[module/powermenu]
type = custom/text
content ="󰐥"
content-font = 2
content-foreground = ${c.green}
click-left = ~/.local/bin/login_script power

[module/loginmenu]
type = custom/text
content ="󰤁"
content-font = 2
content-foreground = ${c.green}
click-left = ~/.local/bin/login_script login

; vim:ft=dosini

